### ISSUE TITLE
Feature Request: Multiway-clustering

### ISSUE THREAD

**Issue by Nosferican** [gragusa/CovarianceMatrices.jl#21]
Would be nice to have this functionality for `StatsBase.StatisticalModel`. A free distribution of the article is [here](http://faculty.econ.ucdavis.edu/faculty/cameron/research/JBESpaper2009version.pdf).

### References
Colin Cameron, Adrian, Jonah B. Gelbach, and Douglas L. Miller. 2011. "Robust Inference
With Multiway Clustering." Journal of Business & Economic Statistics 29 (2): 238-249.
doi:[10.1198/jbes.2010.07136](https://dx.doi.org/10.1198/jbes.2010.07136).

**Comment by Nosferican** [comment]
The code is pretty simple to implement:
Given, `X::AbstractMatrix` the model matrix and `û::AbstractVector` the residuals, one only needs to define `G::AbstractMatrix` which is a cluster defining matrix.
`V = inv(factorize(X.'X)) * X * (û * û.' .* G) * X.' inv(factorize(X.'X))`
and `G` is a symmetric matrix which takes values `true` at `G[i,j]` ⟺ i ^ j share any clusters (same level for any dimension).

**Comment by gragusa** [comment]
Ok. I will look into it shortly

**Comment by Nosferican** [comment]
I actually implemented it some time ago, I could contribute it if you are interested.

**Comment by gragusa** [comment]
Closed by #61
