### ISSUE TITLE
Tests fail on current release

### ISSUE THREAD

**Issue by andreasnoack** [gragusa/CovarianceMatrices.jl#31]
This is partly because `CSV` now returns dataframes with `Union{T,Missing}` columns and partly because of a breaking change in `StatsBase` where `stderr` has been renamed to `stderror`. The former is just a test issue so adding an upper bound at 0.2.2 should be sufficient. The latter requires actual code changes but they are straight forward.

**Comment by gragusa** [comment]
Isn't the change `stderr`->`stderror` in StatsBase 0.22.0? I am not able to run tests in Travis, because StatBase requirement cannot be determined. For some reason, GLM.jl 0.11 is not installed.

**Comment by andreasnoack** [comment]
See https://github.com/JuliaLang/METADATA.jl/pull/14607. With that version of GLM, should also be able to require StatsBase 0.22 and use the new `stderror` function.
