### ISSUE TITLE
Example in the README.md is not working

### ISSUE THREAD

**Issue by a-torgovitsky** [gragusa/CovarianceMatrices.jl#40]
```julia
using CovarianceMatrices
using DataFrames
using Random
Random.seed!(1)
n = 500
x = randn(n,5)
u = Array{Float64}(undef, n)
u[1] = rand()
for j in 2:n
    u[j] = 0.78*u[j-1] + randn()
end
df = DataFrame()
df[:y] = u
for j in enumerate([:x1, :x2, :x3, :x4, :x5])
    df[j[2]] = x[:,j[1]]
end
lm1 = lm(@formula(y~x1+x2+x3+x4+x5), df)
vcov(lm1, ParzenKernel(1.34, prewhiten = true))
```

This incorporates my fix to the example in #39 .
However, the `vcov` command gives this error:
```julia
ERROR: MethodError: no method matching ParzenKernel(::Float64; prewhiten=true)
```
A method `ParzenKernel(::Number)` is found, but when I try that I get
```julia
julia> vcov(lm1, ParzenKernel(1.34))
ERROR: type LmResp has no field wrkresid
```

Do I have the right versions?
```julia
(v1.1) pkg> status CovarianceMatrices
    Status `~/.julia/environments/v1.1/Project.toml`
  [60f91f6f] CovarianceMatrices v0.9.0
  [a93c6f00] DataFrames v0.17.0
  [38e38edf] GLM v1.1.1
  [2913bbd2] StatsBase v0.27.0
  [3eaba693] StatsModels v0.5.0

```

**Comment by gragusa** [comment]
Thanks for reporting this. Which branch have you tested?

**Comment by gragusa** [comment]
Ok. I made several improvements a few months ago that are in the testing
branch (which, however still contains the problematic example). If you use
the package, would you mind trying to use it? Especially the cache
feature....(it is not documented yet, but if you are willing to help I can
write a guide to use the feature).



Giuseppe Ragusa

**Comment by gragusa** [comment]
Ok. Master is in shape. Closing this. I will marge #39 once tests pass.
