### ISSUE TITLE
No Documentation

### ISSUE THREAD

**Issue by MUsmanZahid** [gragusa/CovarianceMatrices.jl#44]
Hi @gragusa there seems to be no documentation for this package.

**Comment by Marco-Congedo** [comment]
Yes please, add or point to documentation.

**Comment by gragusa** [comment]
I added back the documentation for the last tagged version of the package. 

The master branch departs significantly for the last tagged version (0.9.0). Documentation for the master branch (which will be eventually tagged as 1.0) is under development.

**Comment by Marco-Congedo** [comment]
thanks:)
