### ISSUE TITLE
Call for Julia Maintainers to support the Julia Language + the MLH Fellowship

### ISSUE THREAD

**Issue by PaulSoderlind** [gragusa/CovarianceMatrices.jl#50]
https://discourse.julialang.org/t/call-for-julia-maintainers-to-support-the-julia-language-the-mlh-fellowship/40514

This might be a good idea. I would be happy to help out with some of the theoretical aspects, but I don't (yet) understand the API.

**Comment by gragusa** [comment]
@PaulSoderlind that would be fun and useful. But probably may be more interesting to involve students on other projects (I have a GMM package almost done and other time series stuff (dynamic factor models, VAR) that I cannot find the time to finish. In any case, the API of CovarianceMatrices in master is different than that of the registered version — again not much time to document and add some syntactic sugar. If interested .... :-)

**Comment by PaulSoderlind** [comment]
>the API of CovarianceMatrices in master is different than that of the registered version

This seems to work on master:  PR https://github.com/gragusa/CovarianceMatrices.jl/pull/48

**Comment by gragusa** [comment]
@PaulSoderlind  thank you. You PR addresses perfectly the new API and I will merge. The problem is that the API on master breaks the older API. I should probably release 1.0, but I want to be sure that the API is solid. Do you think the API is ok as it is?

**Comment by PaulSoderlind** [comment]
I cannot claim that I have worked through all the aspects of the API, so I cannot really tell. I still think that something like issue https://github.com/gragusa/CovarianceMatrices.jl/issues/49 would be very useful. Personally, I never use glm.
