### ISSUE TITLE
Drop dependency on GLM

### ISSUE THREAD

**Issue by nalimilan** [gragusa/CovarianceMatrices.jl#60]
I was wondering what would be needed to drop the (optional) dependency on GLM. glm.jl seems to contain methods which are type piracy, which isn't great. Also, with https://github.com/JuliaStats/GLM.jl/pull/339 we'd like to drop `TableRegressionModel` in favor of directly returning `LinearModel` and `GeneralizedLinearModel` objects. Would that be a problem for CovarianceMatrices?

Maybe that could be the occasion to fix https://github.com/gragusa/CovarianceMatrices.jl/issues/47 and https://github.com/JuliaStats/GLM.jl/issues/42 by implementing the necessary parts in GLM? Could we also make this more generic so that it works for other packages that implement the StatsAPI/StatsModels API?

**Comment by gragusa** [comment]
I am working on it. I will draft a pull request with the necessary changes. My for [https://github.com/gragusa/GLM.jl](https://github.com/gragusa/GLM.jl) has all the necessary changes to allow CovarianceMatrices.jl to drop the dependence on GLM.jl.
